unbind r
bind r source-file ~/.tmux.conf

#improve colors
set -g default-terminal 'screen-256color'

# start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1

# change leader key to Ctrl-s
set -g prefix C-s

# turn on mouse
set -g mouse on

# change navigation to vim equal vim motions
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

# tmux-sessionizer
bind-key -r f run-shell "tmux neww ~/.scripts/tmux-sessionizer"

# tmux cht.sh
bind-key -r i run-shell "tmux neww ~/.scripts/tmux-cht.sh"

# status bar on top or bottom of the screen
set-option -g status-position top

# use tpm
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'
